/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing FiltersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FiltersApiTests : IDisposable
    {
        private FiltersApi instance;

        public FiltersApiTests()
        {
            instance = new FiltersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FiltersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FiltersApi
            //Assert.IsType<FiltersApi>(instance);
        }

        /// <summary>
        /// Test Filters
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filterId = null;
            //string documentFormat = null;
            //string documentVersion = null;
            //var response = instance.Filters(filterId, documentFormat, documentVersion);
            //Assert.IsType<PiRestFilters>(response);
        }

        /// <summary>
        /// Test FiltersActions
        /// </summary>
        [Fact]
        public void FiltersActionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filterId = null;
            //string parameterGroupId = null;
            //string parameterIds = null;
            //string timeZero = null;
            //string documentFormat = null;
            //string documentVersion = null;
            //var response = instance.FiltersActions(filterId, parameterGroupId, parameterIds, timeZero, documentFormat, documentVersion);
            //Assert.IsType<PiRestActions>(response);
        }
    }
}
