/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Domains
    /// </summary>
    [DataContract(Name = "Domains")]
    public partial class Domains : IEquatable<Domains>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Domains" /> class.
        /// </summary>
        /// <param name="domainAxisValues">Domain Axis Values.</param>
        /// <param name="events">Domain Axis Events.</param>
        public Domains(List<DomainAxisValue> domainAxisValues = default(List<DomainAxisValue>), List<DomainAxisEvent> events = default(List<DomainAxisEvent>))
        {
            this.DomainAxisValues = domainAxisValues;
            this.Events = events;
        }

        /// <summary>
        /// Domain Axis Values
        /// </summary>
        /// <value>Domain Axis Values</value>
        [DataMember(Name = "domainAxisValues", EmitDefaultValue = false)]
        public List<DomainAxisValue> DomainAxisValues { get; set; }

        /// <summary>
        /// Domain Axis Events
        /// </summary>
        /// <value>Domain Axis Events</value>
        [DataMember(Name = "events", EmitDefaultValue = false)]
        public List<DomainAxisEvent> Events { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Domains {\n");
            sb.Append("  DomainAxisValues: ").Append(DomainAxisValues).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Domains);
        }

        /// <summary>
        /// Returns true if Domains instances are equal
        /// </summary>
        /// <param name="input">Instance of Domains to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Domains input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DomainAxisValues == input.DomainAxisValues ||
                    this.DomainAxisValues != null &&
                    input.DomainAxisValues != null &&
                    this.DomainAxisValues.SequenceEqual(input.DomainAxisValues)
                ) && 
                (
                    this.Events == input.Events ||
                    this.Events != null &&
                    input.Events != null &&
                    this.Events.SequenceEqual(input.Events)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DomainAxisValues != null)
                {
                    hashCode = (hashCode * 59) + this.DomainAxisValues.GetHashCode();
                }
                if (this.Events != null)
                {
                    hashCode = (hashCode * 59) + this.Events.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
