/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RatingCurvesStageValues PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_ratingcurves_stage")]
    public partial class PiRestRatingcurvesStage : IEquatable<PiRestRatingcurvesStage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestRatingcurvesStage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestRatingcurvesStage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestRatingcurvesStage" /> class.
        /// </summary>
        /// <param name="stageValues">Stage Values (required).</param>
        public PiRestRatingcurvesStage(List<string> stageValues = default(List<string>))
        {
            // to ensure "stageValues" is required (not null)
            if (stageValues == null)
            {
                throw new ArgumentNullException("stageValues is a required property for PiRestRatingcurvesStage and cannot be null");
            }
            this.StageValues = stageValues;
        }

        /// <summary>
        /// Stage Values
        /// </summary>
        /// <value>Stage Values</value>
        [DataMember(Name = "stageValues", IsRequired = true, EmitDefaultValue = true)]
        public List<string> StageValues { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestRatingcurvesStage {\n");
            sb.Append("  StageValues: ").Append(StageValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestRatingcurvesStage);
        }

        /// <summary>
        /// Returns true if PiRestRatingcurvesStage instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestRatingcurvesStage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestRatingcurvesStage input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.StageValues == input.StageValues ||
                    this.StageValues != null &&
                    input.StageValues != null &&
                    this.StageValues.SequenceEqual(input.StageValues)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StageValues != null)
                {
                    hashCode = (hashCode * 59) + this.StageValues.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
