/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Topology Selected PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_topology_selected")]
    public partial class PiRestTopologySelected : IEquatable<PiRestTopologySelected>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestTopologySelected" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestTopologySelected() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestTopologySelected" /> class.
        /// </summary>
        /// <param name="topologyNodeId">Id of the selected topology node (required).</param>
        public PiRestTopologySelected(string topologyNodeId = default(string))
        {
            // to ensure "topologyNodeId" is required (not null)
            if (topologyNodeId == null)
            {
                throw new ArgumentNullException("topologyNodeId is a required property for PiRestTopologySelected and cannot be null");
            }
            this.TopologyNodeId = topologyNodeId;
        }

        /// <summary>
        /// Id of the selected topology node
        /// </summary>
        /// <value>Id of the selected topology node</value>
        [DataMember(Name = "topologyNodeId", IsRequired = true, EmitDefaultValue = true)]
        public string TopologyNodeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestTopologySelected {\n");
            sb.Append("  TopologyNodeId: ").Append(TopologyNodeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestTopologySelected);
        }

        /// <summary>
        /// Returns true if PiRestTopologySelected instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestTopologySelected to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestTopologySelected input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TopologyNodeId == input.TopologyNodeId ||
                    (this.TopologyNodeId != null &&
                    this.TopologyNodeId.Equals(input.TopologyNodeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TopologyNodeId != null)
                {
                    hashCode = (hashCode * 59) + this.TopologyNodeId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
