/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ArchiveAreasResponse PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_archive_areas")]
    public partial class PiRestArchiveAreas : IEquatable<PiRestArchiveAreas>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestArchiveAreas" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestArchiveAreas() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestArchiveAreas" /> class.
        /// </summary>
        /// <param name="areas">ArchiveAreas (required).</param>
        public PiRestArchiveAreas(List<ArchiveArea> areas = default(List<ArchiveArea>))
        {
            // to ensure "areas" is required (not null)
            if (areas == null)
            {
                throw new ArgumentNullException("areas is a required property for PiRestArchiveAreas and cannot be null");
            }
            this.Areas = areas;
        }

        /// <summary>
        /// ArchiveAreas
        /// </summary>
        /// <value>ArchiveAreas</value>
        [DataMember(Name = "areas", IsRequired = true, EmitDefaultValue = true)]
        public List<ArchiveArea> Areas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestArchiveAreas {\n");
            sb.Append("  Areas: ").Append(Areas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestArchiveAreas);
        }

        /// <summary>
        /// Returns true if PiRestArchiveAreas instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestArchiveAreas to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestArchiveAreas input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Areas == input.Areas ||
                    this.Areas != null &&
                    input.Areas != null &&
                    this.Areas.SequenceEqual(input.Areas)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Areas != null)
                {
                    hashCode = (hashCode * 59) + this.Areas.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
