/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ArchiveExternalNetCDFStorageForecastsResponse PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_archive_externalnetcdfstorageforecasts")]
    public partial class PiRestArchiveExternalnetcdfstorageforecasts : IEquatable<PiRestArchiveExternalnetcdfstorageforecasts>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestArchiveExternalnetcdfstorageforecasts" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestArchiveExternalnetcdfstorageforecasts() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestArchiveExternalnetcdfstorageforecasts" /> class.
        /// </summary>
        /// <param name="externalNetCDFStorageForecasts">External NetCD FStorage Forecasts (required).</param>
        public PiRestArchiveExternalnetcdfstorageforecasts(List<ExternalNetCDFStorageForecast> externalNetCDFStorageForecasts = default(List<ExternalNetCDFStorageForecast>))
        {
            // to ensure "externalNetCDFStorageForecasts" is required (not null)
            if (externalNetCDFStorageForecasts == null)
            {
                throw new ArgumentNullException("externalNetCDFStorageForecasts is a required property for PiRestArchiveExternalnetcdfstorageforecasts and cannot be null");
            }
            this.ExternalNetCDFStorageForecasts = externalNetCDFStorageForecasts;
        }

        /// <summary>
        /// External NetCD FStorage Forecasts
        /// </summary>
        /// <value>External NetCD FStorage Forecasts</value>
        [DataMember(Name = "externalNetCDFStorageForecasts", IsRequired = true, EmitDefaultValue = true)]
        public List<ExternalNetCDFStorageForecast> ExternalNetCDFStorageForecasts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestArchiveExternalnetcdfstorageforecasts {\n");
            sb.Append("  ExternalNetCDFStorageForecasts: ").Append(ExternalNetCDFStorageForecasts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestArchiveExternalnetcdfstorageforecasts);
        }

        /// <summary>
        /// Returns true if PiRestArchiveExternalnetcdfstorageforecasts instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestArchiveExternalnetcdfstorageforecasts to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestArchiveExternalnetcdfstorageforecasts input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ExternalNetCDFStorageForecasts == input.ExternalNetCDFStorageForecasts ||
                    this.ExternalNetCDFStorageForecasts != null &&
                    input.ExternalNetCDFStorageForecasts != null &&
                    this.ExternalNetCDFStorageForecasts.SequenceEqual(input.ExternalNetCDFStorageForecasts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalNetCDFStorageForecasts != null)
                {
                    hashCode = (hashCode * 59) + this.ExternalNetCDFStorageForecasts.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
