/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ProcessdataApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProcessdataApiTests : IDisposable
    {
        private ProcessdataApi instance;

        public ProcessdataApiTests()
        {
            instance = new ProcessdataApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessdataApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProcessdataApi
            //Assert.IsType<ProcessdataApi>(instance);
        }

        /// <summary>
        /// Test Processdata
        /// </summary>
        [Fact]
        public void ProcessdataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string workflowId = null;
            //DateTime? startTime = null;
            //DateTime? endTime = null;
            //string xMin = null;
            //string xMax = null;
            //string yMin = null;
            //string yMax = null;
            //string xCellSize = null;
            //string yCellSize = null;
            //string deleteOutputFolder = null;
            //var response = instance.Processdata(workflowId, startTime, endTime, xMin, xMax, yMin, yMax, xCellSize, yCellSize, deleteOutputFolder);
            //Assert.IsType<string>(response);
        }
    }
}
