/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing SamplesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SamplesApiTests : IDisposable
    {
        private SamplesApi instance;

        public SamplesApiTests()
        {
            instance = new SamplesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SamplesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SamplesApi
            //Assert.IsType<SamplesApi>(instance);
        }

        /// <summary>
        /// Test Samples
        /// </summary>
        [Fact]
        public void SamplesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filterId = null;
            //List<string> sampleIds = null;
            //List<string> locationIds = null;
            //List<string> parameterIds = null;
            //List<string> qualifierIds = null;
            //DateTime? startTime = null;
            //DateTime? endTime = null;
            //DateTime? startCreationTime = null;
            //DateTime? endCreationTime = null;
            //string omitMissing = null;
            //string onlyHeaders = null;
            //string documentFormat = null;
            //string documentVersion = null;
            //var response = instance.Samples(filterId, sampleIds, locationIds, parameterIds, qualifierIds, startTime, endTime, startCreationTime, endCreationTime, omitMissing, onlyHeaders, documentFormat, documentVersion);
            //Assert.IsType<Object>(response);
        }
    }
}
