/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISamplesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample
        /// </summary>
        /// <remarks>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        Object Samples(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0);

        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample
        /// </summary>
        /// <remarks>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> SamplesWithHttpInfo(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISamplesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample
        /// </summary>
        /// <remarks>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> SamplesAsync(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample
        /// </summary>
        /// <remarks>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> SamplesWithHttpInfoAsync(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISamplesApi : ISamplesApiSync, ISamplesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SamplesApi : ISamplesApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SamplesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SamplesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SamplesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SamplesApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SamplesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SamplesApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SamplesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SamplesApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Object</returns>
        public Object Samples(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Object> localVarResponse = SamplesWithHttpInfo(filterId, sampleIds, locationIds, parameterIds, qualifierIds, startTime, endTime, startCreationTime, endCreationTime, omitMissing, onlyHeaders, documentFormat, documentVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> SamplesWithHttpInfo(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/xml",
                "plain/text"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (filterId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "filterId", filterId));
            }
            if (sampleIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "sampleIds", sampleIds));
            }
            if (locationIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "locationIds", locationIds));
            }
            if (parameterIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "parameterIds", parameterIds));
            }
            if (qualifierIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "qualifierIds", qualifierIds));
            }
            if (startTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "startTime", startTime));
            }
            if (endTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "endTime", endTime));
            }
            if (startCreationTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "startCreationTime", startCreationTime));
            }
            if (endCreationTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "endCreationTime", endCreationTime));
            }
            if (omitMissing != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "omitMissing", omitMissing));
            }
            if (onlyHeaders != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "onlyHeaders", onlyHeaders));
            }
            if (documentFormat != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentFormat", documentFormat));
            }
            if (documentVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentVersion", documentVersion));
            }

            localVarRequestOptions.Operation = "SamplesApi.Samples";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/samples", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Samples", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> SamplesAsync(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Object> localVarResponse = await SamplesWithHttpInfoAsync(filterId, sampleIds, locationIds, parameterIds, qualifierIds, startTime, endTime, startCreationTime, endCreationTime, omitMissing, onlyHeaders, documentFormat, documentVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample Get samples filtered by parameters like filterId, sampleId, parameterId and creation time of a sample.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">Filter Id (optional)</param>
        /// <param name="sampleIds">One or more sample ids (optional)</param>
        /// <param name="locationIds">One or more location ids (optional)</param>
        /// <param name="parameterIds">One or more parameter ids (optional)</param>
        /// <param name="qualifierIds">One or more qualifier ids (optional)</param>
        /// <param name="startTime">Start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endTime">End time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="startCreationTime">Creation start time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="endCreationTime">Creation end time. Format: yyyy-MM-ddTHH:mm:ssZ (optional)</param>
        /// <param name="omitMissing">Toggle omitting or returning of missing values in response. (optional)</param>
        /// <param name="onlyHeaders">Toggle to return only header information or also data. (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> SamplesWithHttpInfoAsync(string filterId = default(string), List<string> sampleIds = default(List<string>), List<string> locationIds = default(List<string>), List<string> parameterIds = default(List<string>), List<string> qualifierIds = default(List<string>), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), DateTime? startCreationTime = default(DateTime?), DateTime? endCreationTime = default(DateTime?), string omitMissing = default(string), string onlyHeaders = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/xml",
                "plain/text"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (filterId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "filterId", filterId));
            }
            if (sampleIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "sampleIds", sampleIds));
            }
            if (locationIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "locationIds", locationIds));
            }
            if (parameterIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "parameterIds", parameterIds));
            }
            if (qualifierIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "qualifierIds", qualifierIds));
            }
            if (startTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "startTime", startTime));
            }
            if (endTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "endTime", endTime));
            }
            if (startCreationTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "startCreationTime", startCreationTime));
            }
            if (endCreationTime != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "endCreationTime", endCreationTime));
            }
            if (omitMissing != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "omitMissing", omitMissing));
            }
            if (onlyHeaders != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "onlyHeaders", onlyHeaders));
            }
            if (documentFormat != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentFormat", documentFormat));
            }
            if (documentVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentVersion", documentVersion));
            }

            localVarRequestOptions.Operation = "SamplesApi.Samples";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/samples", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Samples", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
