/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ImportStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImportStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImportStatus
        //private ImportStatus instance;

        public ImportStatusTests()
        {
            // TODO uncomment below to create an instance of ImportStatus
            //instance = new ImportStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImportStatus
        /// </summary>
        [Fact]
        public void ImportStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImportStatus
            //Assert.IsType<ImportStatus>(instance);
        }


        /// <summary>
        /// Test the property 'McId'
        /// </summary>
        [Fact]
        public void McIdTest()
        {
            // TODO unit test for the property 'McId'
        }
        /// <summary>
        /// Test the property 'DataFeed'
        /// </summary>
        [Fact]
        public void DataFeedTest()
        {
            // TODO unit test for the property 'DataFeed'
        }
        /// <summary>
        /// Test the property 'LastImportTime'
        /// </summary>
        [Fact]
        public void LastImportTimeTest()
        {
            // TODO unit test for the property 'LastImportTime'
        }
        /// <summary>
        /// Test the property 'LastFileImported'
        /// </summary>
        [Fact]
        public void LastFileImportedTest()
        {
            // TODO unit test for the property 'LastFileImported'
        }
        /// <summary>
        /// Test the property 'FileRead'
        /// </summary>
        [Fact]
        public void FileReadTest()
        {
            // TODO unit test for the property 'FileRead'
        }
        /// <summary>
        /// Test the property 'FileFailed'
        /// </summary>
        [Fact]
        public void FileFailedTest()
        {
            // TODO unit test for the property 'FileFailed'
        }
        /// <summary>
        /// Test the property 'LastImportTimeBackgroundColor'
        /// </summary>
        [Fact]
        public void LastImportTimeBackgroundColorTest()
        {
            // TODO unit test for the property 'LastImportTimeBackgroundColor'
        }

    }

}
