/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ModuleRunTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModuleRunTimeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModuleRunTime
        //private ModuleRunTime instance;

        public ModuleRunTimeTests()
        {
            // TODO uncomment below to create an instance of ModuleRunTime
            //instance = new ModuleRunTime();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModuleRunTime
        /// </summary>
        [Fact]
        public void ModuleRunTimeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModuleRunTime
            //Assert.IsType<ModuleRunTime>(instance);
        }


        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Fact]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }
        /// <summary>
        /// Test the property 'ModuleInstanceId'
        /// </summary>
        [Fact]
        public void ModuleInstanceIdTest()
        {
            // TODO unit test for the property 'ModuleInstanceId'
        }
        /// <summary>
        /// Test the property 'McId'
        /// </summary>
        [Fact]
        public void McIdTest()
        {
            // TODO unit test for the property 'McId'
        }
        /// <summary>
        /// Test the property 'ExpectedStartTime'
        /// </summary>
        [Fact]
        public void ExpectedStartTimeTest()
        {
            // TODO unit test for the property 'ExpectedStartTime'
        }
        /// <summary>
        /// Test the property 'ExpectedCompletionTime'
        /// </summary>
        [Fact]
        public void ExpectedCompletionTimeTest()
        {
            // TODO unit test for the property 'ExpectedCompletionTime'
        }
        /// <summary>
        /// Test the property 'ExpectedPendingDuration'
        /// </summary>
        [Fact]
        public void ExpectedPendingDurationTest()
        {
            // TODO unit test for the property 'ExpectedPendingDuration'
        }
        /// <summary>
        /// Test the property 'ExpectedRunningDuration'
        /// </summary>
        [Fact]
        public void ExpectedRunningDurationTest()
        {
            // TODO unit test for the property 'ExpectedRunningDuration'
        }

    }

}
