/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PiRestLocationsSelected
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiRestLocationsSelectedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiRestLocationsSelected
        //private PiRestLocationsSelected instance;

        public PiRestLocationsSelectedTests()
        {
            // TODO uncomment below to create an instance of PiRestLocationsSelected
            //instance = new PiRestLocationsSelected();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiRestLocationsSelected
        /// </summary>
        [Fact]
        public void PiRestLocationsSelectedInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiRestLocationsSelected
            //Assert.IsType<PiRestLocationsSelected>(instance);
        }


        /// <summary>
        /// Test the property 'LocationIds'
        /// </summary>
        [Fact]
        public void LocationIdsTest()
        {
            // TODO unit test for the property 'LocationIds'
        }

    }

}
