/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RatingCurveEquation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RatingCurveEquationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RatingCurveEquation
        //private RatingCurveEquation instance;

        public RatingCurveEquationTests()
        {
            // TODO uncomment below to create an instance of RatingCurveEquation
            //instance = new RatingCurveEquation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RatingCurveEquation
        /// </summary>
        [Fact]
        public void RatingCurveEquationInstanceTest()
        {
            // TODO uncomment below to test "IsType" RatingCurveEquation
            //Assert.IsType<RatingCurveEquation>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'MinStage'
        /// </summary>
        [Fact]
        public void MinStageTest()
        {
            // TODO unit test for the property 'MinStage'
        }
        /// <summary>
        /// Test the property 'MaxStage'
        /// </summary>
        [Fact]
        public void MaxStageTest()
        {
            // TODO unit test for the property 'MaxStage'
        }
        /// <summary>
        /// Test the property 'Flag'
        /// </summary>
        [Fact]
        public void FlagTest()
        {
            // TODO unit test for the property 'Flag'
        }
        /// <summary>
        /// Test the property 'Alpha'
        /// </summary>
        [Fact]
        public void AlphaTest()
        {
            // TODO unit test for the property 'Alpha'
        }
        /// <summary>
        /// Test the property 'Cr'
        /// </summary>
        [Fact]
        public void CrTest()
        {
            // TODO unit test for the property 'Cr'
        }
        /// <summary>
        /// Test the property 'Beta'
        /// </summary>
        [Fact]
        public void BetaTest()
        {
            // TODO unit test for the property 'Beta'
        }

    }

}
