/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TimeSeriesParameters PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_parameters_nodes")]
    public partial class PiRestParametersNodes : IEquatable<PiRestParametersNodes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestParametersNodes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestParametersNodes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestParametersNodes" /> class.
        /// </summary>
        /// <param name="version">PI Version (required).</param>
        /// <param name="parameterNodes">ParameterNode (required).</param>
        public PiRestParametersNodes(string version = default(string), List<ParameterNode> parameterNodes = default(List<ParameterNode>))
        {
            // to ensure "version" is required (not null)
            if (version == null)
            {
                throw new ArgumentNullException("version is a required property for PiRestParametersNodes and cannot be null");
            }
            this._Version = version;
            // to ensure "parameterNodes" is required (not null)
            if (parameterNodes == null)
            {
                throw new ArgumentNullException("parameterNodes is a required property for PiRestParametersNodes and cannot be null");
            }
            this.ParameterNodes = parameterNodes;
        }

        /// <summary>
        /// PI Version
        /// </summary>
        /// <value>PI Version</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = true)]
        public string _Version { get; set; }

        /// <summary>
        /// ParameterNode
        /// </summary>
        /// <value>ParameterNode</value>
        [DataMember(Name = "parameterNodes", IsRequired = true, EmitDefaultValue = true)]
        public List<ParameterNode> ParameterNodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestParametersNodes {\n");
            sb.Append("  _Version: ").Append(_Version).Append("\n");
            sb.Append("  ParameterNodes: ").Append(ParameterNodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestParametersNodes);
        }

        /// <summary>
        /// Returns true if PiRestParametersNodes instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestParametersNodes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestParametersNodes input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this._Version == input._Version ||
                    (this._Version != null &&
                    this._Version.Equals(input._Version))
                ) && 
                (
                    this.ParameterNodes == input.ParameterNodes ||
                    this.ParameterNodes != null &&
                    input.ParameterNodes != null &&
                    this.ParameterNodes.SequenceEqual(input.ParameterNodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Version != null)
                {
                    hashCode = (hashCode * 59) + this._Version.GetHashCode();
                }
                if (this.ParameterNodes != null)
                {
                    hashCode = (hashCode * 59) + this.ParameterNodes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
