/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RatingCurvesResponse PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_ratingcurves")]
    public partial class PiRestRatingcurves : IEquatable<PiRestRatingcurves>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestRatingcurves" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestRatingcurves() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestRatingcurves" /> class.
        /// </summary>
        /// <param name="timeZone">the timezone.</param>
        /// <param name="ratingCurves">ratingCurves (required).</param>
        public PiRestRatingcurves(string timeZone = default(string), List<RatingCurve> ratingCurves = default(List<RatingCurve>))
        {
            // to ensure "ratingCurves" is required (not null)
            if (ratingCurves == null)
            {
                throw new ArgumentNullException("ratingCurves is a required property for PiRestRatingcurves and cannot be null");
            }
            this.RatingCurves = ratingCurves;
            this.TimeZone = timeZone;
        }

        /// <summary>
        /// the timezone
        /// </summary>
        /// <value>the timezone</value>
        [DataMember(Name = "timeZone", EmitDefaultValue = false)]
        public string TimeZone { get; set; }

        /// <summary>
        /// Gets or Sets RatingCurves
        /// </summary>
        [DataMember(Name = "ratingCurves", IsRequired = true, EmitDefaultValue = true)]
        public List<RatingCurve> RatingCurves { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestRatingcurves {\n");
            sb.Append("  TimeZone: ").Append(TimeZone).Append("\n");
            sb.Append("  RatingCurves: ").Append(RatingCurves).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestRatingcurves);
        }

        /// <summary>
        /// Returns true if PiRestRatingcurves instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestRatingcurves to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestRatingcurves input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TimeZone == input.TimeZone ||
                    (this.TimeZone != null &&
                    this.TimeZone.Equals(input.TimeZone))
                ) && 
                (
                    this.RatingCurves == input.RatingCurves ||
                    this.RatingCurves != null &&
                    input.RatingCurves != null &&
                    this.RatingCurves.SequenceEqual(input.RatingCurves)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TimeZone != null)
                {
                    hashCode = (hashCode * 59) + this.TimeZone.GetHashCode();
                }
                if (this.RatingCurves != null)
                {
                    hashCode = (hashCode * 59) + this.RatingCurves.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
