/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ImportStatusResponse PI_JSON
    /// </summary>
    [DataContract(Name = "pi_rest_importstatus")]
    public partial class PiRestImportstatus : IEquatable<PiRestImportstatus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestImportstatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PiRestImportstatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestImportstatus" /> class.
        /// </summary>
        /// <param name="importStatus">importStatus (required).</param>
        public PiRestImportstatus(List<ImportStatus> importStatus = default(List<ImportStatus>))
        {
            // to ensure "importStatus" is required (not null)
            if (importStatus == null)
            {
                throw new ArgumentNullException("importStatus is a required property for PiRestImportstatus and cannot be null");
            }
            this.ImportStatus = importStatus;
        }

        /// <summary>
        /// Gets or Sets ImportStatus
        /// </summary>
        [DataMember(Name = "importStatus", IsRequired = true, EmitDefaultValue = true)]
        public List<ImportStatus> ImportStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PiRestImportstatus {\n");
            sb.Append("  ImportStatus: ").Append(ImportStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestImportstatus);
        }

        /// <summary>
        /// Returns true if PiRestImportstatus instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestImportstatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestImportstatus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ImportStatus == input.ImportStatus ||
                    this.ImportStatus != null &&
                    input.ImportStatus != null &&
                    this.ImportStatus.SequenceEqual(input.ImportStatus)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ImportStatus != null)
                {
                    hashCode = (hashCode * 59) + this.ImportStatus.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
