/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PiRestWebocConfigurationComponentsInner
    /// </summary>
    [JsonConverter(typeof(PiRestWebocConfigurationComponentsInnerJsonConverter))]
    [DataContract(Name = "pi_rest_weboc_configuration_components_inner")]
    public partial class PiRestWebocConfigurationComponentsInner : AbstractOpenAPISchema, IEquatable<PiRestWebocConfigurationComponentsInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestWebocConfigurationComponentsInner" /> class
        /// with the <see cref="DataViewerConfig" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DataViewerConfig.</param>
        public PiRestWebocConfigurationComponentsInner(DataViewerConfig actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestWebocConfigurationComponentsInner" /> class
        /// with the <see cref="SpatialDisplayConfig" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SpatialDisplayConfig.</param>
        public PiRestWebocConfigurationComponentsInner(SpatialDisplayConfig actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestWebocConfigurationComponentsInner" /> class
        /// with the <see cref="SchematicStatusDisplayConfig" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SchematicStatusDisplayConfig.</param>
        public PiRestWebocConfigurationComponentsInner(SchematicStatusDisplayConfig actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestWebocConfigurationComponentsInner" /> class
        /// with the <see cref="TimeSeriesDisplayConfig" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TimeSeriesDisplayConfig.</param>
        public PiRestWebocConfigurationComponentsInner(TimeSeriesDisplayConfig actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestWebocConfigurationComponentsInner" /> class
        /// with the <see cref="SystemMonitorConfig" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SystemMonitorConfig.</param>
        public PiRestWebocConfigurationComponentsInner(SystemMonitorConfig actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PiRestWebocConfigurationComponentsInner" /> class
        /// with the <see cref="ArchiveDisplayConfig" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ArchiveDisplayConfig.</param>
        public PiRestWebocConfigurationComponentsInner(ArchiveDisplayConfig actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(ArchiveDisplayConfig))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DataViewerConfig))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SchematicStatusDisplayConfig))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SpatialDisplayConfig))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SystemMonitorConfig))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TimeSeriesDisplayConfig))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: ArchiveDisplayConfig, DataViewerConfig, SchematicStatusDisplayConfig, SpatialDisplayConfig, SystemMonitorConfig, TimeSeriesDisplayConfig");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `DataViewerConfig`. If the actual instance is not `DataViewerConfig`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DataViewerConfig</returns>
        public DataViewerConfig GetDataViewerConfig()
        {
            return (DataViewerConfig)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SpatialDisplayConfig`. If the actual instance is not `SpatialDisplayConfig`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SpatialDisplayConfig</returns>
        public SpatialDisplayConfig GetSpatialDisplayConfig()
        {
            return (SpatialDisplayConfig)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SchematicStatusDisplayConfig`. If the actual instance is not `SchematicStatusDisplayConfig`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SchematicStatusDisplayConfig</returns>
        public SchematicStatusDisplayConfig GetSchematicStatusDisplayConfig()
        {
            return (SchematicStatusDisplayConfig)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `TimeSeriesDisplayConfig`. If the actual instance is not `TimeSeriesDisplayConfig`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TimeSeriesDisplayConfig</returns>
        public TimeSeriesDisplayConfig GetTimeSeriesDisplayConfig()
        {
            return (TimeSeriesDisplayConfig)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SystemMonitorConfig`. If the actual instance is not `SystemMonitorConfig`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SystemMonitorConfig</returns>
        public SystemMonitorConfig GetSystemMonitorConfig()
        {
            return (SystemMonitorConfig)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ArchiveDisplayConfig`. If the actual instance is not `ArchiveDisplayConfig`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ArchiveDisplayConfig</returns>
        public ArchiveDisplayConfig GetArchiveDisplayConfig()
        {
            return (ArchiveDisplayConfig)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PiRestWebocConfigurationComponentsInner {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, PiRestWebocConfigurationComponentsInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of PiRestWebocConfigurationComponentsInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of PiRestWebocConfigurationComponentsInner</returns>
        public static PiRestWebocConfigurationComponentsInner FromJson(string jsonString)
        {
            PiRestWebocConfigurationComponentsInner newPiRestWebocConfigurationComponentsInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newPiRestWebocConfigurationComponentsInner;
            }

            try
            {
                newPiRestWebocConfigurationComponentsInner = new PiRestWebocConfigurationComponentsInner(JsonConvert.DeserializeObject<ArchiveDisplayConfig>(jsonString, PiRestWebocConfigurationComponentsInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPiRestWebocConfigurationComponentsInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ArchiveDisplayConfig: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPiRestWebocConfigurationComponentsInner = new PiRestWebocConfigurationComponentsInner(JsonConvert.DeserializeObject<DataViewerConfig>(jsonString, PiRestWebocConfigurationComponentsInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPiRestWebocConfigurationComponentsInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DataViewerConfig: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPiRestWebocConfigurationComponentsInner = new PiRestWebocConfigurationComponentsInner(JsonConvert.DeserializeObject<SchematicStatusDisplayConfig>(jsonString, PiRestWebocConfigurationComponentsInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPiRestWebocConfigurationComponentsInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SchematicStatusDisplayConfig: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPiRestWebocConfigurationComponentsInner = new PiRestWebocConfigurationComponentsInner(JsonConvert.DeserializeObject<SpatialDisplayConfig>(jsonString, PiRestWebocConfigurationComponentsInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPiRestWebocConfigurationComponentsInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SpatialDisplayConfig: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPiRestWebocConfigurationComponentsInner = new PiRestWebocConfigurationComponentsInner(JsonConvert.DeserializeObject<SystemMonitorConfig>(jsonString, PiRestWebocConfigurationComponentsInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPiRestWebocConfigurationComponentsInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SystemMonitorConfig: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPiRestWebocConfigurationComponentsInner = new PiRestWebocConfigurationComponentsInner(JsonConvert.DeserializeObject<TimeSeriesDisplayConfig>(jsonString, PiRestWebocConfigurationComponentsInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPiRestWebocConfigurationComponentsInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TimeSeriesDisplayConfig: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PiRestWebocConfigurationComponentsInner);
        }

        /// <summary>
        /// Returns true if PiRestWebocConfigurationComponentsInner instances are equal
        /// </summary>
        /// <param name="input">Instance of PiRestWebocConfigurationComponentsInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PiRestWebocConfigurationComponentsInner input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for PiRestWebocConfigurationComponentsInner
    /// </summary>
    public class PiRestWebocConfigurationComponentsInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(PiRestWebocConfigurationComponentsInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return PiRestWebocConfigurationComponentsInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
