/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocationsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument
        /// </summary>
        /// <remarks>
        /// Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PiRestLocations</returns>
        PiRestLocations Locations(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0);

        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument
        /// </summary>
        /// <remarks>
        /// Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PiRestLocations</returns>
        ApiResponse<PiRestLocations> LocationsWithHttpInfo(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocationsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument
        /// </summary>
        /// <remarks>
        /// Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PiRestLocations</returns>
        System.Threading.Tasks.Task<PiRestLocations> LocationsAsync(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument
        /// </summary>
        /// <remarks>
        /// Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PiRestLocations)</returns>
        System.Threading.Tasks.Task<ApiResponse<PiRestLocations>> LocationsWithHttpInfoAsync(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocationsApi : ILocationsApiSync, ILocationsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LocationsApi : ILocationsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LocationsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LocationsApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LocationsApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocationsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public LocationsApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PiRestLocations</returns>
        public PiRestLocations Locations(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<PiRestLocations> localVarResponse = LocationsWithHttpInfo(filterId, parameterIds, parameterGroupId, showAttributes, includeLocationRelations, includeTimeDependency, documentFormat, documentVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PiRestLocations</returns>
        public Org.OpenAPITools.Client.ApiResponse<PiRestLocations> LocationsWithHttpInfo(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/geojson",
                "application/xml",
                "plain/text"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (filterId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "filterId", filterId));
            }
            if (parameterIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "parameterIds", parameterIds));
            }
            if (parameterGroupId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "parameterGroupId", parameterGroupId));
            }
            if (showAttributes != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "showAttributes", showAttributes));
            }
            if (includeLocationRelations != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "includeLocationRelations", includeLocationRelations));
            }
            if (includeTimeDependency != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "includeTimeDependency", includeTimeDependency));
            }
            if (documentFormat != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentFormat", documentFormat));
            }
            if (documentVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentVersion", documentVersion));
            }

            localVarRequestOptions.Operation = "LocationsApi.Locations";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PiRestLocations>("/locations", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Locations", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PiRestLocations</returns>
        public async System.Threading.Tasks.Task<PiRestLocations> LocationsAsync(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<PiRestLocations> localVarResponse = await LocationsWithHttpInfoAsync(filterId, parameterIds, parameterGroupId, showAttributes, includeLocationRelations, includeTimeDependency, documentFormat, documentVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get locations that are available for the &#39;filterId&#39; argument Get locations that are available for the &#39;filterId&#39; argument. Locations are also returned if no time series are available for a location in the filter. If not filterId is passed then all locations configured in the pre-defined filter will be returned.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="filterId">An existing subfilter of the default filter id (optional)</param>
        /// <param name="parameterIds">One or more parameters which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="parameterGroupId">The parameter group id which will be used to filter the time series sets in the filter (optional)</param>
        /// <param name="showAttributes">Show location attributes (optional)</param>
        /// <param name="includeLocationRelations">Include location relations (optional)</param>
        /// <param name="includeTimeDependency">Include time depency (optional)</param>
        /// <param name="documentFormat">Supported Document Format: PI_XML, PI_JSON, GEO_JSON,  (optional)</param>
        /// <param name="documentVersion">Document Version. Latest version is: 1.33 (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PiRestLocations)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<PiRestLocations>> LocationsWithHttpInfoAsync(string filterId = default(string), string parameterIds = default(string), string parameterGroupId = default(string), string showAttributes = default(string), string includeLocationRelations = default(string), string includeTimeDependency = default(string), string documentFormat = default(string), string documentVersion = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/geojson",
                "application/xml",
                "plain/text"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (filterId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "filterId", filterId));
            }
            if (parameterIds != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "parameterIds", parameterIds));
            }
            if (parameterGroupId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "parameterGroupId", parameterGroupId));
            }
            if (showAttributes != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "showAttributes", showAttributes));
            }
            if (includeLocationRelations != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "includeLocationRelations", includeLocationRelations));
            }
            if (includeTimeDependency != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "includeTimeDependency", includeTimeDependency));
            }
            if (documentFormat != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentFormat", documentFormat));
            }
            if (documentVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "documentVersion", documentVersion));
            }

            localVarRequestOptions.Operation = "LocationsApi.Locations";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PiRestLocations>("/locations", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Locations", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
