/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ArchiveParameters200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArchiveParameters200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArchiveParameters200Response
        //private ArchiveParameters200Response instance;

        public ArchiveParameters200ResponseTests()
        {
            // TODO uncomment below to create an instance of ArchiveParameters200Response
            //instance = new ArchiveParameters200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArchiveParameters200Response
        /// </summary>
        [Fact]
        public void ArchiveParameters200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArchiveParameters200Response
            //Assert.IsType<ArchiveParameters200Response>(instance);
        }


        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

    }

}
