/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ArchiveProductsMetadataEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArchiveProductsMetadataEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArchiveProductsMetadataEntry
        //private ArchiveProductsMetadataEntry instance;

        public ArchiveProductsMetadataEntryTests()
        {
            // TODO uncomment below to create an instance of ArchiveProductsMetadataEntry
            //instance = new ArchiveProductsMetadataEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArchiveProductsMetadataEntry
        /// </summary>
        [Fact]
        public void ArchiveProductsMetadataEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArchiveProductsMetadataEntry
            //Assert.IsType<ArchiveProductsMetadataEntry>(instance);
        }


        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'AreaId'
        /// </summary>
        [Fact]
        public void AreaIdTest()
        {
            // TODO unit test for the property 'AreaId'
        }
        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Fact]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
        /// <summary>
        /// Test the property 'RelativePathMetaDataFile'
        /// </summary>
        [Fact]
        public void RelativePathMetaDataFileTest()
        {
            // TODO unit test for the property 'RelativePathMetaDataFile'
        }
        /// <summary>
        /// Test the property 'RelativePathProducts'
        /// </summary>
        [Fact]
        public void RelativePathProductsTest()
        {
            // TODO unit test for the property 'RelativePathProducts'
        }
        /// <summary>
        /// Test the property 'DataSetCreationTime'
        /// </summary>
        [Fact]
        public void DataSetCreationTimeTest()
        {
            // TODO unit test for the property 'DataSetCreationTime'
        }
        /// <summary>
        /// Test the property 'TimeZero'
        /// </summary>
        [Fact]
        public void TimeZeroTest()
        {
            // TODO unit test for the property 'TimeZero'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

    }

}
