/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LocationGeoJsonRelation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationGeoJsonRelationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LocationGeoJsonRelation
        //private LocationGeoJsonRelation instance;

        public LocationGeoJsonRelationTests()
        {
            // TODO uncomment below to create an instance of LocationGeoJsonRelation
            //instance = new LocationGeoJsonRelation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LocationGeoJsonRelation
        /// </summary>
        [Fact]
        public void LocationGeoJsonRelationInstanceTest()
        {
            // TODO uncomment below to test "IsType" LocationGeoJsonRelation
            //Assert.IsType<LocationGeoJsonRelation>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RelatedLocationId'
        /// </summary>
        [Fact]
        public void RelatedLocationIdTest()
        {
            // TODO unit test for the property 'RelatedLocationId'
        }
        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Fact]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }
        /// <summary>
        /// Test the property 'EndDateTime'
        /// </summary>
        [Fact]
        public void EndDateTimeTest()
        {
            // TODO unit test for the property 'EndDateTime'
        }

    }

}
