/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ParameterNodeParent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParameterNodeParentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParameterNodeParent
        //private ParameterNodeParent instance;

        public ParameterNodeParentTests()
        {
            // TODO uncomment below to create an instance of ParameterNodeParent
            //instance = new ParameterNodeParent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParameterNodeParent
        /// </summary>
        [Fact]
        public void ParameterNodeParentInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParameterNodeParent
            //Assert.IsType<ParameterNodeParent>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
