/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ParameterNodeChild
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParameterNodeChildTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParameterNodeChild
        //private ParameterNodeChild instance;

        public ParameterNodeChildTests()
        {
            // TODO uncomment below to create an instance of ParameterNodeChild
            //instance = new ParameterNodeChild();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParameterNodeChild
        /// </summary>
        [Fact]
        public void ParameterNodeChildInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParameterNodeChild
            //Assert.IsType<ParameterNodeChild>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
