/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PiRestRatingcurvesStage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiRestRatingcurvesStageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiRestRatingcurvesStage
        //private PiRestRatingcurvesStage instance;

        public PiRestRatingcurvesStageTests()
        {
            // TODO uncomment below to create an instance of PiRestRatingcurvesStage
            //instance = new PiRestRatingcurvesStage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiRestRatingcurvesStage
        /// </summary>
        [Fact]
        public void PiRestRatingcurvesStageInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiRestRatingcurvesStage
            //Assert.IsType<PiRestRatingcurvesStage>(instance);
        }


        /// <summary>
        /// Test the property 'StageValues'
        /// </summary>
        [Fact]
        public void StageValuesTest()
        {
            // TODO unit test for the property 'StageValues'
        }

    }

}
