/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PiRestActions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiRestActionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiRestActions
        //private PiRestActions instance;

        public PiRestActionsTests()
        {
            // TODO uncomment below to create an instance of PiRestActions
            //instance = new PiRestActions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiRestActions
        /// </summary>
        [Fact]
        public void PiRestActionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiRestActions
            //Assert.IsType<PiRestActions>(instance);
        }


        /// <summary>
        /// Test the property 'ResultsNotAvailableForRequest'
        /// </summary>
        [Fact]
        public void ResultsNotAvailableForRequestTest()
        {
            // TODO unit test for the property 'ResultsNotAvailableForRequest'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
