/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PiRestTimeseries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiRestTimeseriesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiRestTimeseries
        //private PiRestTimeseries instance;

        public PiRestTimeseriesTests()
        {
            // TODO uncomment below to create an instance of PiRestTimeseries
            //instance = new PiRestTimeseries();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiRestTimeseries
        /// </summary>
        [Fact]
        public void PiRestTimeseriesInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiRestTimeseries
            //Assert.IsType<PiRestTimeseries>(instance);
        }


        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Fact]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }
        /// <summary>
        /// Test the property 'TimeSeries'
        /// </summary>
        [Fact]
        public void TimeSeriesTest()
        {
            // TODO unit test for the property 'TimeSeries'
        }

    }

}
