/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PiRestWebocConfigurationComponentsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiRestWebocConfigurationComponentsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiRestWebocConfigurationComponentsInner
        //private PiRestWebocConfigurationComponentsInner instance;

        public PiRestWebocConfigurationComponentsInnerTests()
        {
            // TODO uncomment below to create an instance of PiRestWebocConfigurationComponentsInner
            //instance = new PiRestWebocConfigurationComponentsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiRestWebocConfigurationComponentsInner
        /// </summary>
        [Fact]
        public void PiRestWebocConfigurationComponentsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiRestWebocConfigurationComponentsInner
            //Assert.IsType<PiRestWebocConfigurationComponentsInner>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'ForecastLegend'
        /// </summary>
        [Fact]
        public void ForecastLegendTest()
        {
            // TODO unit test for the property 'ForecastLegend'
        }
        /// <summary>
        /// Test the property 'Subplots'
        /// </summary>
        [Fact]
        public void SubplotsTest()
        {
            // TODO unit test for the property 'Subplots'
        }

    }

}
