/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PiRestLocations
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PiRestLocationsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PiRestLocations
        //private PiRestLocations instance;

        public PiRestLocationsTests()
        {
            // TODO uncomment below to create an instance of PiRestLocations
            //instance = new PiRestLocations();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PiRestLocations
        /// </summary>
        [Fact]
        public void PiRestLocationsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PiRestLocations
            //Assert.IsType<PiRestLocations>(instance);
        }


        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'GeoDatum'
        /// </summary>
        [Fact]
        public void GeoDatumTest()
        {
            // TODO unit test for the property 'GeoDatum'
        }
        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Fact]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }

    }

}
