/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RatingCurveRow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RatingCurveRowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RatingCurveRow
        //private RatingCurveRow instance;

        public RatingCurveRowTests()
        {
            // TODO uncomment below to create an instance of RatingCurveRow
            //instance = new RatingCurveRow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RatingCurveRow
        /// </summary>
        [Fact]
        public void RatingCurveRowInstanceTest()
        {
            // TODO uncomment below to test "IsType" RatingCurveRow
            //Assert.IsType<RatingCurveRow>(instance);
        }


        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Fact]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }
        /// <summary>
        /// Test the property 'Discharge'
        /// </summary>
        [Fact]
        public void DischargeTest()
        {
            // TODO unit test for the property 'Discharge'
        }
        /// <summary>
        /// Test the property 'LogScaleStageOffset'
        /// </summary>
        [Fact]
        public void LogScaleStageOffsetTest()
        {
            // TODO unit test for the property 'LogScaleStageOffset'
        }
        /// <summary>
        /// Test the property 'Flag'
        /// </summary>
        [Fact]
        public void FlagTest()
        {
            // TODO unit test for the property 'Flag'
        }

    }

}
