/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RatingCurve
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RatingCurveTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RatingCurve
        //private RatingCurve instance;

        public RatingCurveTests()
        {
            // TODO uncomment below to create an instance of RatingCurve
            //instance = new RatingCurve();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RatingCurve
        /// </summary>
        [Fact]
        public void RatingCurveInstanceTest()
        {
            // TODO uncomment below to test "IsType" RatingCurve
            //Assert.IsType<RatingCurve>(instance);
        }


        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Table'
        /// </summary>
        [Fact]
        public void TableTest()
        {
            // TODO unit test for the property 'Table'
        }
        /// <summary>
        /// Test the property 'Equations'
        /// </summary>
        [Fact]
        public void EquationsTest()
        {
            // TODO unit test for the property 'Equations'
        }

    }

}
