/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TimeSeriesDisplaySubplot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeSeriesDisplaySubplotTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeSeriesDisplaySubplot
        //private TimeSeriesDisplaySubplot instance;

        public TimeSeriesDisplaySubplotTests()
        {
            // TODO uncomment below to create an instance of TimeSeriesDisplaySubplot
            //instance = new TimeSeriesDisplaySubplot();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeSeriesDisplaySubplot
        /// </summary>
        [Fact]
        public void TimeSeriesDisplaySubplotInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeSeriesDisplaySubplot
            //Assert.IsType<TimeSeriesDisplaySubplot>(instance);
        }


        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

    }

}
