/*
 * Delft-FEWS Web Services REST API v1
 *
 * Delft-FEWS Web Services REST API v1. For more information see: https://publicwiki.deltares.nl/x/fwNdBw
 *
 * The version of the OpenAPI document: v1-2023-05-03T00:04:18Z
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TopologyNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopologyNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TopologyNode
        //private TopologyNode instance;

        public TopologyNodeTests()
        {
            // TODO uncomment below to create an instance of TopologyNode
            //instance = new TopologyNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TopologyNode
        /// </summary>
        [Fact]
        public void TopologyNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" TopologyNode
            //Assert.IsType<TopologyNode>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'WorkflowId'
        /// </summary>
        [Fact]
        public void WorkflowIdTest()
        {
            // TODO unit test for the property 'WorkflowId'
        }
        /// <summary>
        /// Test the property 'LocalRun'
        /// </summary>
        [Fact]
        public void LocalRunTest()
        {
            // TODO unit test for the property 'LocalRun'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'DisplayId'
        /// </summary>
        [Fact]
        public void DisplayIdTest()
        {
            // TODO unit test for the property 'DisplayId'
        }
        /// <summary>
        /// Test the property 'DisplayGroups'
        /// </summary>
        [Fact]
        public void DisplayGroupsTest()
        {
            // TODO unit test for the property 'DisplayGroups'
        }
        /// <summary>
        /// Test the property 'TopologyNodes'
        /// </summary>
        [Fact]
        public void TopologyNodesTest()
        {
            // TODO unit test for the property 'TopologyNodes'
        }

    }

}
